var
	elasticsearch = require('elasticsearch')
	, client = new elasticsearch.Client({

	})
	, fs = require('fs')
	, callback = function (err, result) {
		if (err) {
			console.log(err);
		}
		fs.writeFile('result.json', JSON.stringify(result, null, 4));
	}
	, async = require('async');

async.series([
	function (ok) {
		client.indices.delete({
			index : 'db'
		}, ok);
	},
	function (ok) {
		client.indices.create({
			index : 'db',
			body : {
				
			    "settings" : {
					"number_of_shards" : 1,
					"analysis" : {
						"filter" : {
							"my_shingle_filter" : {
								"type" : "shingle",
								"min_shingle_size" : 2,
								"max_shingle_size" : 2,
								"output_unigrams" : true
							},
							"autocomplete_filter" : {
								"type" : "edge_ngram",
								"min_gram" : 1,
								"max_gram" : 20
							}
						},
						"analyzer" : {
							"my_shingle_analyzer" : {
								"type" : "custom",
								"tokenizer" : "standard",
								"filter" : [
									"lowercase",
									"my_shingle_filter"
								]
							},
							"autocomplete" : {
								"type" : "custom",
								"tokenizer" : "standard",
								"filter" : [
									"lowercase",
									"autocomplete_filter"
								]
							}
						}
					}
				},
				"mappings" : {
					"jobs" : {
						"properties" : {
							"jobTitle" : {
								"type" : "multi_field",
								"fields" : {
									"jobTitle" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "english"
									},
									"shingle" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "my_shingle_analyzer"
									},
									"ngram" : {
										"type" : "string",
										"analyzer" : "autocomplete"
									}
								}
							},
							"companyName" : {
								"type" : "multi_field",
								"fields" : {
									"companyName" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "standard"
									},
									"shingle" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "my_shingle_analyzer"
									},
									"ngram" : {
										"type" : "string",
										"analyzer" : "autocomplete"
									}
								}
							},
							"location" : {
								"type" : "multi_field",
								"fields" : {
									"location" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "standard"
									},
									"shingle" : {
										"type" : "string",
										"index" : "analyzed",
										"analyzer" : "my_shingle_analyzer"
									},
									"ngram" : {
										"type" : "string",
										"analyzer" : "autocomplete"
									}
								}
							}
						}
					}
				}
				
			}
		}, ok);
	},
	function (ok) {
		async.eachSeries([{"jobTitle":"Marketing Manager","companyName":"Photobug","location":"Polje"},
{"jobTitle":"Assistant Professor","companyName":"Quire","location":"Oenunu"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Edgepulse","location":"Muḩammad Āghah Wuluswālī"},
{"jobTitle":"Research Associate","companyName":"Leexo","location":"Arrah"},
{"jobTitle":"Marketing Assistant","companyName":"Thoughtbridge","location":"Trzemeszno"},
{"jobTitle":"Administrative Assistant I","companyName":"Divape","location":"Kafr Zaytā"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Zoonoodle","location":"Passo"},
{"jobTitle":"Dental Hygienist","companyName":"Yombu","location":"Protección"},
{"jobTitle":"Environmental Specialist","companyName":"Feedbug","location":"Companhia de Baixo"},
{"jobTitle":"Office Assistant III","companyName":"Realmix","location":"Apurawan"},
{"jobTitle":"Technical Writer","companyName":"Chatterpoint","location":"Ode"},
{"jobTitle":"Research Associate","companyName":"Meevee","location":"Dao’er"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Blogpad","location":"Uyuni"},
{"jobTitle":"Automation Specialist II","companyName":"Edgetag","location":"Ashkāsham"},
{"jobTitle":"Account Executive","companyName":"Quaxo","location":"Paraguaçu Paulista"},
{"jobTitle":"VP Marketing","companyName":"Digitube","location":"Hofors"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Wikizz","location":"Tanzhou"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Gevee","location":"João Pessoa"},
{"jobTitle":"Programmer III","companyName":"Omba","location":"Fare"},
{"jobTitle":"Editor","companyName":"Talane","location":"Jingling"},
{"jobTitle":"Project Manager","companyName":"Riffpath","location":"Daireaux"},
{"jobTitle":"Graphic Designer","companyName":"Buzzbean","location":"Dalakovo"},
{"jobTitle":"Senior Sales Associate","companyName":"Twiyo","location":"Nelidovo"},
{"jobTitle":"Operator","companyName":"Yodel","location":"Labansari"},
{"jobTitle":"Account Coordinator","companyName":"Blognation","location":"Sathon"},
{"jobTitle":"Senior Cost Accountant","companyName":"Eire","location":"Solna"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Wikivu","location":"Aketi"},
{"jobTitle":"Structural Engineer","companyName":"Twitterbridge","location":"Kobayashi"},
{"jobTitle":"Software Consultant","companyName":"Devcast","location":"Log pri Brezovici"},
{"jobTitle":"Web Developer I","companyName":"Bluezoom","location":"Kpalimé"},
{"jobTitle":"Administrative Assistant I","companyName":"Fadeo","location":"Rakiv Lis"},
{"jobTitle":"Marketing Manager","companyName":"Dynabox","location":"Trzebnica"},
{"jobTitle":"Health Coach III","companyName":"Oyoba","location":"Oslo"},
{"jobTitle":"Human Resources Manager","companyName":"Livepath","location":"Jönköping"},
{"jobTitle":"Structural Engineer","companyName":"Topdrive","location":"Lokatadho"},
{"jobTitle":"Environmental Specialist","companyName":"Yamia","location":"Yangping"},
{"jobTitle":"Quality Engineer","companyName":"Blogspan","location":"Zhaigang"},
{"jobTitle":"Senior Developer","companyName":"Topiczoom","location":"Fanrong"},
{"jobTitle":"Recruiter","companyName":"Quamba","location":"Kawangkoan"},
{"jobTitle":"Environmental Tech","companyName":"Youfeed","location":"Baiyin"},
{"jobTitle":"Systems Administrator II","companyName":"Bubblebox","location":"Zerok-Alakadari"},
{"jobTitle":"VP Product Management","companyName":"Podcat","location":"Runan"},
{"jobTitle":"Compensation Analyst","companyName":"Meeveo","location":"Callao"},
{"jobTitle":"Research Assistant II","companyName":"Babbleset","location":"Alor Star"},
{"jobTitle":"Biostatistician IV","companyName":"Rhyzio","location":"Pieksämäki"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Bubblebox","location":"Matou"},
{"jobTitle":"Project Manager","companyName":"Camimbo","location":"Stan-Bekhtemir"},
{"jobTitle":"Assistant Media Planner","companyName":"Fliptune","location":"Jijiang"},
{"jobTitle":"Geological Engineer","companyName":"Zoozzy","location":"Jatirejo"},
{"jobTitle":"Account Coordinator","companyName":"Centimia","location":"Lixiqiao"},
{"jobTitle":"Graphic Designer","companyName":"Quinu","location":"Huitong"},
{"jobTitle":"Automation Specialist I","companyName":"Oba","location":"Tabon"},
{"jobTitle":"Community Outreach Specialist","companyName":"Pixoboo","location":"Zouma"},
{"jobTitle":"Clinical Specialist","companyName":"Voonix","location":"San Eugenio"},
{"jobTitle":"Environmental Tech","companyName":"Realbuzz","location":"San Gabriel"},
{"jobTitle":"Health Coach IV","companyName":"Devshare","location":"Trasak"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Twitterworks","location":"Longtou"},
{"jobTitle":"Financial Analyst","companyName":"Bubbletube","location":"Lyaskovets"},
{"jobTitle":"Chemical Engineer","companyName":"Vipe","location":"Wysoka"},
{"jobTitle":"Automation Specialist IV","companyName":"Jabbertype","location":"Bastia"},
{"jobTitle":"Sales Associate","companyName":"Oloo","location":"Khoyniki"},
{"jobTitle":"Senior Editor","companyName":"Eazzy","location":"Eindhoven"},
{"jobTitle":"Software Consultant","companyName":"Cogibox","location":"Simod"},
{"jobTitle":"Assistant Media Planner","companyName":"Rhynyx","location":"Chunjing"},
{"jobTitle":"Statistician II","companyName":"Dabshots","location":"San Cosme y Damián"},
{"jobTitle":"Executive Secretary","companyName":"Eare","location":"Lidong"},
{"jobTitle":"Statistician II","companyName":"Kwideo","location":"Santa Marta"},
{"jobTitle":"Librarian","companyName":"Dazzlesphere","location":"Dazaifu"},
{"jobTitle":"Account Coordinator","companyName":"Riffpath","location":"Maogang"},
{"jobTitle":"Programmer III","companyName":"Lazz","location":"Cosmópolis"},
{"jobTitle":"Marketing Assistant","companyName":"Fiveclub","location":"Silgueiros"},
{"jobTitle":"VP Sales","companyName":"Topicware","location":"Darpas"},
{"jobTitle":"Programmer Analyst II","companyName":"Eimbee","location":"Banjar Bau Kawan"},
{"jobTitle":"Quality Engineer","companyName":"Rooxo","location":"Jinta"},
{"jobTitle":"Information Systems Manager","companyName":"Tanoodle","location":"Płock"},
{"jobTitle":"Help Desk Technician","companyName":"Quaxo","location":"Pérez"},
{"jobTitle":"Office Assistant IV","companyName":"Yadel","location":"Bokaa"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Mynte","location":"Bailu"},
{"jobTitle":"Human Resources Assistant II","companyName":"Aimbo","location":"Sujiatun"},
{"jobTitle":"Sales Representative","companyName":"Lajo","location":"Mingshan"},
{"jobTitle":"Actuary","companyName":"Riffwire","location":"Zuwārah"},
{"jobTitle":"Programmer Analyst II","companyName":"Meevee","location":"Revelstoke"},
{"jobTitle":"VP Accounting","companyName":"Jabbercube","location":"Masis"},
{"jobTitle":"Data Coordiator","companyName":"Viva","location":"Berlin"},
{"jobTitle":"Nurse Practicioner","companyName":"Topicshots","location":"Adirejo"},
{"jobTitle":"Developer III","companyName":"Rhynyx","location":"Cibogo"},
{"jobTitle":"Research Assistant I","companyName":"Rhybox","location":"Franco da Rocha"},
{"jobTitle":"General Manager","companyName":"Agimba","location":"New Panamao"},
{"jobTitle":"Administrative Assistant IV","companyName":"Jayo","location":"Two Hills"},
{"jobTitle":"Recruiting Manager","companyName":"Oyondu","location":"Shijiang"},
{"jobTitle":"VP Product Management","companyName":"Rhynoodle","location":"Saint-Denis"},
{"jobTitle":"Senior Quality Engineer","companyName":"InnoZ","location":"Shakhty"},
{"jobTitle":"Assistant Media Planner","companyName":"Linklinks","location":"Dubinino"},
{"jobTitle":"Technical Writer","companyName":"Mybuzz","location":"San Vicente"},
{"jobTitle":"Information Systems Manager","companyName":"Trilith","location":"Bang Phae"},
{"jobTitle":"Web Developer I","companyName":"Cogidoo","location":"Caldelas"},
{"jobTitle":"Senior Developer","companyName":"Latz","location":"Danderyd"},
{"jobTitle":"Civil Engineer","companyName":"Voonix","location":"Babagan"},
{"jobTitle":"Technical Writer","companyName":"Eare","location":"Qingyang"},
{"jobTitle":"Operator","companyName":"Jayo","location":"Huangliu"},
{"jobTitle":"Social Worker","companyName":"Thoughtmix","location":"Sanhe"},
{"jobTitle":"Editor","companyName":"Mybuzz","location":"Dodola"},
{"jobTitle":"Pharmacist","companyName":"Quimba","location":"Isaka"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Flashspan","location":"Kwatarkwashi"},
{"jobTitle":"Financial Advisor","companyName":"Buzzbean","location":"Eišiškės"},
{"jobTitle":"Chief Design Engineer","companyName":"Browsebug","location":"Puyo"},
{"jobTitle":"Recruiter","companyName":"Topicblab","location":"Shaguotun"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Riffpath","location":"Iwŏn-ŭp"},
{"jobTitle":"Project Manager","companyName":"Cogibox","location":"Calauan"},
{"jobTitle":"Assistant Media Planner","companyName":"Vinte","location":"Shijing"},
{"jobTitle":"Sales Representative","companyName":"Buzzdog","location":"Nanhu"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Yoveo","location":"Thị Trấn Quảng Uyên"},
{"jobTitle":"Senior Sales Associate","companyName":"Avamm","location":"Weixin"},
{"jobTitle":"Product Engineer","companyName":"Photofeed","location":"Durrës"},
{"jobTitle":"Web Developer II","companyName":"Abata","location":"Promissão"},
{"jobTitle":"Quality Control Specialist","companyName":"Meedoo","location":"Genteng"},
{"jobTitle":"Paralegal","companyName":"Innotype","location":"Liudaogou"},
{"jobTitle":"Research Associate","companyName":"Shufflester","location":"Vrýses"},
{"jobTitle":"Quality Engineer","companyName":"Photospace","location":"Sar-e Pul"},
{"jobTitle":"Paralegal","companyName":"Fanoodle","location":"Mojosari"},
{"jobTitle":"Financial Analyst","companyName":"Dynabox","location":"Ciudad Arce"},
{"jobTitle":"Recruiter","companyName":"JumpXS","location":"Huiwen"},
{"jobTitle":"Food Chemist","companyName":"Leexo","location":"Mabayo"},
{"jobTitle":"Electrical Engineer","companyName":"Quire","location":"Mafa"},
{"jobTitle":"Legal Assistant","companyName":"Thoughtmix","location":"Gouqi"},
{"jobTitle":"Civil Engineer","companyName":"Youspan","location":"Chigorodó"},
{"jobTitle":"Director of Sales","companyName":"Devify","location":"Bantar"},
{"jobTitle":"Pharmacist","companyName":"Flashpoint","location":"Macari"},
{"jobTitle":"Financial Analyst","companyName":"Livefish","location":"Waipukang"},
{"jobTitle":"Quality Control Specialist","companyName":"Zoomcast","location":"Urungpigang"},
{"jobTitle":"Geological Engineer","companyName":"Tambee","location":"Neyrīz"},
{"jobTitle":"Help Desk Operator","companyName":"Vinte","location":"Duobaoshan"},
{"jobTitle":"Developer III","companyName":"Twimm","location":"La Foa"},
{"jobTitle":"Nurse Practicioner","companyName":"Pixope","location":"Toulouse"},
{"jobTitle":"Electrical Engineer","companyName":"Riffpath","location":"Tomingad"},
{"jobTitle":"Internal Auditor","companyName":"Topicware","location":"Cartagena"},
{"jobTitle":"Technical Writer","companyName":"Meedoo","location":"Seminole"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Skyndu","location":"Stan-Bekhtemir"},
{"jobTitle":"Teacher","companyName":"Jaxnation","location":"Sapporo"},
{"jobTitle":"Recruiter","companyName":"Kazio","location":"Karangasem"},
{"jobTitle":"Statistician IV","companyName":"Meezzy","location":"Akron"},
{"jobTitle":"Tax Accountant","companyName":"Buzzbean","location":"Michałowice"},
{"jobTitle":"Quality Control Specialist","companyName":"Yambee","location":"Várzea da Palma"},
{"jobTitle":"Project Manager","companyName":"Avaveo","location":"Roma"},
{"jobTitle":"VP Product Management","companyName":"Myworks","location":"Thị Trấn Hà Trung"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Thoughtblab","location":"Youxi"},
{"jobTitle":"Software Test Engineer III","companyName":"Zoonoodle","location":"Brzozów"},
{"jobTitle":"VP Sales","companyName":"Yamia","location":"Terek"},
{"jobTitle":"Speech Pathologist","companyName":"Quamba","location":"Zhuxi"},
{"jobTitle":"Administrative Assistant I","companyName":"Realblab","location":"Tambakromo"},
{"jobTitle":"Account Representative II","companyName":"Tagtune","location":"Pukou"},
{"jobTitle":"Marketing Assistant","companyName":"Dynava","location":"Marki"},
{"jobTitle":"Media Manager IV","companyName":"Trilia","location":"Macedo de Cavaleiros"},
{"jobTitle":"Junior Executive","companyName":"Lazzy","location":"Were"},
{"jobTitle":"Teacher","companyName":"Jayo","location":"Paris 20"},
{"jobTitle":"Computer Systems Analyst II","companyName":"Zoozzy","location":"Kanchanaburi"},
{"jobTitle":"Geological Engineer","companyName":"Trunyx","location":"Nong Kung Si"},
{"jobTitle":"Teacher","companyName":"Realpoint","location":"Wincrange"},
{"jobTitle":"Office Assistant III","companyName":"Avavee","location":"Blessington"},
{"jobTitle":"Executive Secretary","companyName":"Dabshots","location":"Oemollo"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Dabtype","location":"Talghar"},
{"jobTitle":"Media Manager I","companyName":"Roomm","location":"Chuquitira"},
{"jobTitle":"Executive Secretary","companyName":"Trilith","location":"Garland"},
{"jobTitle":"Registered Nurse","companyName":"Meevee","location":"Żabieniec"},
{"jobTitle":"Paralegal","companyName":"Skiptube","location":"San Pedro"},
{"jobTitle":"Help Desk Operator","companyName":"Kare","location":"Korhogo"},
{"jobTitle":"Quality Control Specialist","companyName":"Fiveclub","location":"Isawa"},
{"jobTitle":"Human Resources Assistant I","companyName":"Innojam","location":"Tucson"},
{"jobTitle":"Tax Accountant","companyName":"Tagfeed","location":"Bāgh-e Maīdān"},
{"jobTitle":"Software Engineer I","companyName":"Voonte","location":"Targanice"},
{"jobTitle":"Senior Editor","companyName":"Oyope","location":"Santa Nino"},
{"jobTitle":"Assistant Manager","companyName":"Zazio","location":"Göteborg"},
{"jobTitle":"Pharmacist","companyName":"Feedfire","location":"Duko"},
{"jobTitle":"Internal Auditor","companyName":"Rhynoodle","location":"Artashat"},
{"jobTitle":"VP Quality Control","companyName":"Jabbertype","location":"Mariara"},
{"jobTitle":"Systems Administrator IV","companyName":"Devbug","location":"Farmahīn"},
{"jobTitle":"Recruiter","companyName":"Avavee","location":"Onsŏng"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Babblestorm","location":"Binitinan"},
{"jobTitle":"Accounting Assistant IV","companyName":"Tavu","location":"Krajan Langenharjo"},
{"jobTitle":"Teacher","companyName":"Skaboo","location":"Banraeaba Village"},
{"jobTitle":"Account Executive","companyName":"Fatz","location":"Novaya Usman’"},
{"jobTitle":"Programmer II","companyName":"Brainsphere","location":"Wenceslau Braz"},
{"jobTitle":"Accountant II","companyName":"Eimbee","location":"Baratan"},
{"jobTitle":"Senior Sales Associate","companyName":"Skimia","location":"Qo‘qon"},
{"jobTitle":"Administrative Officer","companyName":"Skyndu","location":"Las Lomas"},
{"jobTitle":"Operator","companyName":"Topicware","location":"Kabuynan"},
{"jobTitle":"Senior Editor","companyName":"Buzzster","location":"Nancy"},
{"jobTitle":"Occupational Therapist","companyName":"Skivee","location":"Fenoarivo Be"},
{"jobTitle":"Operator","companyName":"Trudeo","location":"Libei"},
{"jobTitle":"Editor","companyName":"Skinte","location":"Taramana"},
{"jobTitle":"Registered Nurse","companyName":"Skidoo","location":"El Congo"},
{"jobTitle":"Teacher","companyName":"Jatri","location":"Mancilang"},
{"jobTitle":"Assistant Media Planner","companyName":"Browsedrive","location":"Bordeaux"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Izio","location":"Osogbo"},
{"jobTitle":"VP Product Management","companyName":"Plambee","location":"Zhongguan"},
{"jobTitle":"Clinical Specialist","companyName":"Eadel","location":"Qingguang"},
{"jobTitle":"Executive Secretary","companyName":"Ailane","location":"Ljusdal"},
{"jobTitle":"VP Quality Control","companyName":"Browsetype","location":"Ramat Yishay"},
{"jobTitle":"Teacher","companyName":"Fadeo","location":"Vale Mourão"},
{"jobTitle":"Engineer III","companyName":"Quinu","location":"Quinarayan"},
{"jobTitle":"Financial Advisor","companyName":"Skajo","location":"Ryūgasaki"},
{"jobTitle":"Database Administrator III","companyName":"Vimbo","location":"Zhuping"},
{"jobTitle":"Geological Engineer","companyName":"Gevee","location":"Laixi"},
{"jobTitle":"Nurse Practicioner","companyName":"Brainbox","location":"Astanajapura"},
{"jobTitle":"Executive Secretary","companyName":"Mynte","location":"Wensu"},
{"jobTitle":"Assistant Manager","companyName":"Edgewire","location":"Árta"},
{"jobTitle":"Senior Financial Analyst","companyName":"Aimbo","location":"Dalumangcob"},
{"jobTitle":"Recruiting Manager","companyName":"Zoomzone","location":"Kiikala"},
{"jobTitle":"Senior Editor","companyName":"Jaxbean","location":"Tujing"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Voomm","location":"Bayabas"},
{"jobTitle":"Associate Professor","companyName":"Wordware","location":"Jrashen"},
{"jobTitle":"Administrative Officer","companyName":"Twitterwire","location":"Shinao"},
{"jobTitle":"Staff Accountant II","companyName":"Quinu","location":"Vellinge"},
{"jobTitle":"Junior Executive","companyName":"Skidoo","location":"Huangcun"},
{"jobTitle":"Recruiting Manager","companyName":"Realbuzz","location":"Asempapan"},
{"jobTitle":"General Manager","companyName":"Twinte","location":"Perm"},
{"jobTitle":"Web Designer III","companyName":"Meezzy","location":"Placencia"},
{"jobTitle":"Assistant Manager","companyName":"Camido","location":"Huaidian"},
{"jobTitle":"Programmer Analyst I","companyName":"Jabberstorm","location":"Chhāgalnāiya"},
{"jobTitle":"Research Associate","companyName":"Babbleset","location":"Lijiang"},
{"jobTitle":"VP Quality Control","companyName":"Mycat","location":"Älvsjö"},
{"jobTitle":"Environmental Tech","companyName":"Topicstorm","location":"Bida"},
{"jobTitle":"Systems Administrator I","companyName":"Quatz","location":"Dresden"},
{"jobTitle":"Sales Associate","companyName":"Jaloo","location":"Krasnyye Chetai"},
{"jobTitle":"Engineer II","companyName":"Oozz","location":"Orsay"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Jaxbean","location":"Kozel’shchyna"},
{"jobTitle":"Executive Secretary","companyName":"Avamba","location":"Stockholm"},
{"jobTitle":"Recruiting Manager","companyName":"Jamia","location":"Xinfu"},
{"jobTitle":"Developer I","companyName":"Pixonyx","location":"Ualog"},
{"jobTitle":"Assistant Professor","companyName":"Voolia","location":"Haicheng"},
{"jobTitle":"Research Assistant I","companyName":"Oodoo","location":"Ciparakan"},
{"jobTitle":"Desktop Support Technician","companyName":"Omba","location":"Qianjia"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Feedbug","location":"Kolbano"},
{"jobTitle":"Technical Writer","companyName":"Zoovu","location":"Sabae"},
{"jobTitle":"Community Outreach Specialist","companyName":"Jayo","location":"Béoumi"},
{"jobTitle":"Statistician III","companyName":"Blogtag","location":"Parapat"},
{"jobTitle":"Operator","companyName":"Thoughtworks","location":"Kayukembang"},
{"jobTitle":"Software Engineer II","companyName":"Riffwire","location":"Pradera"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Rhyloo","location":"Colonia Mauricio José Troche"},
{"jobTitle":"Geological Engineer","companyName":"Meevee","location":"Setonokalong"},
{"jobTitle":"Graphic Designer","companyName":"Thoughtstorm","location":"Stockholm"},
{"jobTitle":"Environmental Tech","companyName":"Quaxo","location":"Enköping"},
{"jobTitle":"Community Outreach Specialist","companyName":"LiveZ","location":"Jiangjing"},
{"jobTitle":"Software Consultant","companyName":"Avaveo","location":"La Ligua"},
{"jobTitle":"Budget/Accounting Analyst III","companyName":"Topiczoom","location":"Wielbark"},
{"jobTitle":"Associate Professor","companyName":"Flashdog","location":"Kaznějov"},
{"jobTitle":"Account Coordinator","companyName":"Eimbee","location":"Lubichowo"},
{"jobTitle":"Accountant III","companyName":"Yambee","location":"El Refugio"},
{"jobTitle":"Geological Engineer","companyName":"Quire","location":"Magalalag"},
{"jobTitle":"Systems Administrator II","companyName":"Wordtune","location":"Dzel"},
{"jobTitle":"Teacher","companyName":"Brainlounge","location":"Yanggu"},
{"jobTitle":"Budget/Accounting Analyst IV","companyName":"Mybuzz","location":"Parang"},
{"jobTitle":"GIS Technical Architect","companyName":"Trilia","location":"Yamagata-shi"},
{"jobTitle":"Legal Assistant","companyName":"Nlounge","location":"Borowno"},
{"jobTitle":"VP Marketing","companyName":"Leexo","location":"Ar Rawḑah"},
{"jobTitle":"Operator","companyName":"Meevee","location":"Otun"},
{"jobTitle":"Senior Cost Accountant","companyName":"Yadel","location":"Daet"},
{"jobTitle":"Web Designer IV","companyName":"Layo","location":"Liangchahe"},
{"jobTitle":"Database Administrator I","companyName":"Cogidoo","location":"Baidian"},
{"jobTitle":"Project Manager","companyName":"BlogXS","location":"Nerekhta"},
{"jobTitle":"Product Engineer","companyName":"Skinder","location":"Kabuynan"},
{"jobTitle":"Research Assistant II","companyName":"Thoughtworks","location":"Taoyuan"},
{"jobTitle":"Software Consultant","companyName":"Kamba","location":"Aranđelovac"},
{"jobTitle":"Quality Control Specialist","companyName":"Gevee","location":"Bolilao"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Bluejam","location":"Guanmian"},
{"jobTitle":"VP Marketing","companyName":"Skidoo","location":"Tucaní"},
{"jobTitle":"Project Manager","companyName":"Rhynoodle","location":"Mohammedia"},
{"jobTitle":"Sales Representative","companyName":"Yabox","location":"Arroyo Seco"},
{"jobTitle":"Cost Accountant","companyName":"Lazzy","location":"Rockford"},
{"jobTitle":"Financial Analyst","companyName":"Meevee","location":"Novokayakent"},
{"jobTitle":"Accounting Assistant III","companyName":"Quatz","location":"Wrocław"},
{"jobTitle":"Senior Sales Associate","companyName":"Fivebridge","location":"Cravinhos"},
{"jobTitle":"General Manager","companyName":"Trilia","location":"Lampihung"},
{"jobTitle":"Teacher","companyName":"Skinder","location":"Junzhuang"},
{"jobTitle":"Clinical Specialist","companyName":"Jamia","location":"Itapemirim"},
{"jobTitle":"Clinical Specialist","companyName":"Skippad","location":"Malaruhatan"},
{"jobTitle":"Librarian","companyName":"Layo","location":"Seka"},
{"jobTitle":"Engineer II","companyName":"Trilith","location":"Al Jumaylīyah"},
{"jobTitle":"Assistant Manager","companyName":"Miboo","location":"São Miguel"},
{"jobTitle":"Budget/Accounting Analyst IV","companyName":"Centimia","location":"Dubravica"},
{"jobTitle":"Senior Quality Engineer","companyName":"Kazio","location":"Tieremu"},
{"jobTitle":"Senior Quality Engineer","companyName":"Dablist","location":"Carolina"},
{"jobTitle":"Staff Scientist","companyName":"Buzzbean","location":"Graz"},
{"jobTitle":"Paralegal","companyName":"Podcat","location":"Ifanadiana"},
{"jobTitle":"Recruiting Manager","companyName":"Realmix","location":"Ngawi"},
{"jobTitle":"GIS Technical Architect","companyName":"Linklinks","location":"Fernández"},
{"jobTitle":"Legal Assistant","companyName":"Realcube","location":"Picton"},
{"jobTitle":"Analyst Programmer","companyName":"Kamba","location":"Banjar Bau Kawan"},
{"jobTitle":"Human Resources Manager","companyName":"Lazz","location":"Tangpu"},
{"jobTitle":"Structural Engineer","companyName":"Trilith","location":"Barţa‘ah ash Sharqīyah"},
{"jobTitle":"Clinical Specialist","companyName":"Jabbersphere","location":"Ogwashi-Uku"},
{"jobTitle":"Design Engineer","companyName":"Plajo","location":"Potulando"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Voonte","location":"Vlissingen"},
{"jobTitle":"Environmental Tech","companyName":"Mymm","location":"Anren Chengguanzhen"},
{"jobTitle":"Internal Auditor","companyName":"Thoughtmix","location":"Laugar"},
{"jobTitle":"Legal Assistant","companyName":"Oozz","location":"Kuningan"},
{"jobTitle":"Account Representative II","companyName":"Mita","location":"Itapuranga"},
{"jobTitle":"Systems Administrator III","companyName":"Gabvine","location":"Zavet"},
{"jobTitle":"Project Manager","companyName":"Zoomdog","location":"Beauharnois"},
{"jobTitle":"Director of Sales","companyName":"Mynte","location":"Skogås"},
{"jobTitle":"Statistician I","companyName":"Eidel","location":"Nagato"},
{"jobTitle":"Account Executive","companyName":"Camido","location":"El Adelanto"},
{"jobTitle":"Account Representative II","companyName":"Voomm","location":"Wuyo"},
{"jobTitle":"Product Engineer","companyName":"Kwinu","location":"Qinshi"},
{"jobTitle":"Sales Associate","companyName":"Buzzbean","location":"Sijing"},
{"jobTitle":"Technical Writer","companyName":"Eare","location":"Zhonggongmiao"},
{"jobTitle":"Research Associate","companyName":"Devpoint","location":"Campelos"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Jabbercube","location":"Ribeirão Pires"},
{"jobTitle":"Senior Developer","companyName":"Fiveclub","location":"Alexandria"},
{"jobTitle":"VP Accounting","companyName":"Bluejam","location":"Tarata"},
{"jobTitle":"Civil Engineer","companyName":"Flipstorm","location":"Poroshkovo"},
{"jobTitle":"Human Resources Manager","companyName":"Edgeify","location":"Xinrong"},
{"jobTitle":"Electrical Engineer","companyName":"Eadel","location":"Madīnat Sittah Uktūbar"},
{"jobTitle":"Marketing Assistant","companyName":"Kare","location":"Massaranduba"},
{"jobTitle":"Statistician I","companyName":"Zoomcast","location":"Qızılhacılı"},
{"jobTitle":"Quality Control Specialist","companyName":"Dablist","location":"Trà Vinh"},
{"jobTitle":"Financial Analyst","companyName":"Photobug","location":"Yilan"},
{"jobTitle":"Electrical Engineer","companyName":"Flashdog","location":"Jiefang"},
{"jobTitle":"Legal Assistant","companyName":"Eidel","location":"Além"},
{"jobTitle":"Office Assistant IV","companyName":"Wordtune","location":"Taboão da Serra"},
{"jobTitle":"Help Desk Operator","companyName":"Aimbu","location":"Reno"},
{"jobTitle":"Web Developer II","companyName":"Jaxworks","location":"Anfu"},
{"jobTitle":"Food Chemist","companyName":"Kimia","location":"Trzebinia"},
{"jobTitle":"Nurse","companyName":"Abata","location":"Krasnyy Oktyabr’"},
{"jobTitle":"Librarian","companyName":"Twinte","location":"Torre"},
{"jobTitle":"VP Marketing","companyName":"Dazzlesphere","location":"Tualeu"},
{"jobTitle":"Assistant Media Planner","companyName":"Eidel","location":"Barra do Bugres"},
{"jobTitle":"Community Outreach Specialist","companyName":"Rooxo","location":"Shimotoda"},
{"jobTitle":"Librarian","companyName":"Mydeo","location":"Garbów"},
{"jobTitle":"Legal Assistant","companyName":"Yakijo","location":"Červenka"},
{"jobTitle":"Structural Engineer","companyName":"Voolia","location":"Grazhdanskoye"},
{"jobTitle":"VP Quality Control","companyName":"Eire","location":"Libenge"},
{"jobTitle":"Financial Advisor","companyName":"Tagtune","location":"Cruces"},
{"jobTitle":"Account Executive","companyName":"Jetpulse","location":"San Alejandro"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Gabtype","location":"Sionogan"},
{"jobTitle":"Account Representative II","companyName":"Blogspan","location":"Kakhovka"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Quimm","location":"Soio"},
{"jobTitle":"VP Product Management","companyName":"Edgepulse","location":"Dusun Desa Bunter"},
{"jobTitle":"Design Engineer","companyName":"Skipfire","location":"Polevskoy"},
{"jobTitle":"Design Engineer","companyName":"Viva","location":"Srbinovo"},
{"jobTitle":"Actuary","companyName":"Myworks","location":"Xinchang"},
{"jobTitle":"Speech Pathologist","companyName":"Innojam","location":"Miyang"},
{"jobTitle":"Tax Accountant","companyName":"Bubbletube","location":"San Diego"},
{"jobTitle":"Recruiting Manager","companyName":"Vitz","location":"Hellevoetsluis"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Twiyo","location":"Tuatuka"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Voomm","location":"Pułtusk"},
{"jobTitle":"Graphic Designer","companyName":"Eamia","location":"Charlotte Amalie"},
{"jobTitle":"VP Marketing","companyName":"Agivu","location":"Jedlnia-Letnisko"},
{"jobTitle":"Data Coordiator","companyName":"Skidoo","location":"Santo Niño"},
{"jobTitle":"Compensation Analyst","companyName":"Katz","location":"Dawuhan"},
{"jobTitle":"Statistician IV","companyName":"Shufflester","location":"Zaoshi"},
{"jobTitle":"Research Assistant II","companyName":"Devshare","location":"Shatian"},
{"jobTitle":"Programmer Analyst I","companyName":"Divape","location":"Wilamowice"},
{"jobTitle":"Product Engineer","companyName":"Wordify","location":"Karolinka"},
{"jobTitle":"Teacher","companyName":"Kwimbee","location":"Sungai Raya"},
{"jobTitle":"Accountant III","companyName":"Livetube","location":"Cijapar"},
{"jobTitle":"Product Engineer","companyName":"Realmix","location":"Puńsk"},
{"jobTitle":"Civil Engineer","companyName":"Tekfly","location":"Elliot"},
{"jobTitle":"Account Representative IV","companyName":"Dynabox","location":"Pokrovskoye"},
{"jobTitle":"Senior Quality Engineer","companyName":"Devpoint","location":"Tabia"},
{"jobTitle":"Environmental Tech","companyName":"Edgeify","location":"Estombar"},
{"jobTitle":"Account Representative IV","companyName":"Browsebug","location":"Bacong"},
{"jobTitle":"Social Worker","companyName":"Skyble","location":"Padangbatung"},
{"jobTitle":"Associate Professor","companyName":"Realcube","location":"Nishi-Tokyo-shi"},
{"jobTitle":"Librarian","companyName":"Thoughtmix","location":"Chimen"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Yakidoo","location":"Luopu"},
{"jobTitle":"Research Nurse","companyName":"Livetube","location":"Hpa-an"},
{"jobTitle":"Occupational Therapist","companyName":"Wordpedia","location":"Hunkuyi"},
{"jobTitle":"Financial Advisor","companyName":"Devcast","location":"Arias"},
{"jobTitle":"Office Assistant I","companyName":"Mycat","location":"Drezdenko"},
{"jobTitle":"Database Administrator II","companyName":"Devbug","location":"Rongdoi"},
{"jobTitle":"Associate Professor","companyName":"Gabspot","location":"Pulau Pinang"},
{"jobTitle":"Systems Administrator III","companyName":"Zoombox","location":"Langqi"},
{"jobTitle":"Professor","companyName":"Jabbersphere","location":"Ketapang"},
{"jobTitle":"Social Worker","companyName":"Janyx","location":"Bangolo"},
{"jobTitle":"Occupational Therapist","companyName":"Plajo","location":"Pasongsongan"},
{"jobTitle":"Research Associate","companyName":"Voomm","location":"Valleymount"},
{"jobTitle":"Database Administrator I","companyName":"Twinte","location":"Shuangtian"},
{"jobTitle":"Quality Engineer","companyName":"Izio","location":"Samoljica"},
{"jobTitle":"Help Desk Technician","companyName":"Linkbridge","location":"Harar"},
{"jobTitle":"Automation Specialist I","companyName":"Eire","location":"Gyangkar"},
{"jobTitle":"Internal Auditor","companyName":"Livetube","location":"Vyzhnytsya"},
{"jobTitle":"Compensation Analyst","companyName":"Edgetag","location":"Muyinga"},
{"jobTitle":"Environmental Specialist","companyName":"Wordtune","location":"Les Clayes-sous-Bois"},
{"jobTitle":"Structural Engineer","companyName":"Gigashots","location":"Chitose"},
{"jobTitle":"Geological Engineer","companyName":"Thoughtbeat","location":"Torbeyevo"},
{"jobTitle":"Analyst Programmer","companyName":"Yoveo","location":"Tame"},
{"jobTitle":"Internal Auditor","companyName":"Edgewire","location":"Sarajevo"},
{"jobTitle":"Research Associate","companyName":"Lazzy","location":"Sukamaju Kidul"},
{"jobTitle":"Compensation Analyst","companyName":"Babbleset","location":"Conde"},
{"jobTitle":"Design Engineer","companyName":"Vinte","location":"Vancouver"},
{"jobTitle":"Software Engineer III","companyName":"Flashset","location":"Okrouhlice"},
{"jobTitle":"Human Resources Assistant II","companyName":"Mydeo","location":"Sobreira"},
{"jobTitle":"Paralegal","companyName":"Twitterlist","location":"Fanzhen"},
{"jobTitle":"Marketing Assistant","companyName":"Zoovu","location":"Wamba"},
{"jobTitle":"Geologist I","companyName":"Rhyloo","location":"Aţ Ţawāḩīn"},
{"jobTitle":"Human Resources Assistant IV","companyName":"Linktype","location":"Krajan"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Bluejam","location":"Tinawagan"},
{"jobTitle":"Junior Executive","companyName":"Thoughtworks","location":"Sonlit"},
{"jobTitle":"Help Desk Technician","companyName":"Edgeify","location":"Dishnā"},
{"jobTitle":"Geological Engineer","companyName":"Edgepulse","location":"Sieradza"},
{"jobTitle":"Professor","companyName":"Brainsphere","location":"Chandra"},
{"jobTitle":"Teacher","companyName":"Feednation","location":"Roldanillo"},
{"jobTitle":"Recruiter","companyName":"Riffpath","location":"Žamberk"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Zooveo","location":"Mardā"},
{"jobTitle":"Project Manager","companyName":"Twimm","location":"Alexandria"},
{"jobTitle":"Information Systems Manager","companyName":"Einti","location":"Binabaan"},
{"jobTitle":"Engineer II","companyName":"Brightdog","location":"Pakemitan Dua"},
{"jobTitle":"Systems Administrator II","companyName":"Jazzy","location":"Xiaoshan"},
{"jobTitle":"Statistician IV","companyName":"Zoovu","location":"Round Rock"},
{"jobTitle":"Recruiter","companyName":"Livetube","location":"Jagna"},
{"jobTitle":"Help Desk Technician","companyName":"Yakitri","location":"Umeå"},
{"jobTitle":"Desktop Support Technician","companyName":"Youspan","location":"Nunbaundelha"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Kazio","location":"Suva Reka"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Twimm","location":"Vysotskoye"},
{"jobTitle":"Legal Assistant","companyName":"Tagfeed","location":"Valdemārpils"},
{"jobTitle":"Chemical Engineer","companyName":"Omba","location":"Hlusk"},
{"jobTitle":"Design Engineer","companyName":"Skajo","location":"Yantianhe"},
{"jobTitle":"Engineer IV","companyName":"Pixoboo","location":"Pangkalan"},
{"jobTitle":"Senior Sales Associate","companyName":"Skidoo","location":"Luocheng"},
{"jobTitle":"Programmer II","companyName":"Avavee","location":"Châtillon"},
{"jobTitle":"Account Coordinator","companyName":"Blogtags","location":"Hovtashen"},
{"jobTitle":"Dental Hygienist","companyName":"Omba","location":"Stari Grad"},
{"jobTitle":"Structural Engineer","companyName":"Photobean","location":"Póvoa de Penela"},
{"jobTitle":"Quality Control Specialist","companyName":"Fivespan","location":"Koga"},
{"jobTitle":"Assistant Professor","companyName":"Flipstorm","location":"Aix-en-Provence"},
{"jobTitle":"Electrical Engineer","companyName":"Jaxbean","location":"Haikou"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Skimia","location":"Ad Dilam"},
{"jobTitle":"Accountant I","companyName":"Zoozzy","location":"Anoek"},
{"jobTitle":"Civil Engineer","companyName":"Jabbersphere","location":"Kanganpur"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Twitterwire","location":"Châlons-en-Champagne"},
{"jobTitle":"Staff Accountant IV","companyName":"Latz","location":"Baoji"},
{"jobTitle":"Structural Engineer","companyName":"Izio","location":"Lille"},
{"jobTitle":"Recruiting Manager","companyName":"Gabspot","location":"Mengxi"},
{"jobTitle":"Technical Writer","companyName":"Riffpedia","location":"Kotakaya Dua"},
{"jobTitle":"Food Chemist","companyName":"Photobug","location":"Sanxi"},
{"jobTitle":"Geological Engineer","companyName":"Gigabox","location":"Ōyama"},
{"jobTitle":"Editor","companyName":"Wordtune","location":"Krajan Rowokangkung"},
{"jobTitle":"VP Sales","companyName":"Demivee","location":"Hluhluwe"},
{"jobTitle":"VP Quality Control","companyName":"Livepath","location":"Tapes"},
{"jobTitle":"Information Systems Manager","companyName":"Ntags","location":"Czerniewice"},
{"jobTitle":"Assistant Professor","companyName":"Yata","location":"Libice nad Cidlinou"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Eamia","location":"Xinshao"},
{"jobTitle":"Graphic Designer","companyName":"Browseblab","location":"Nova Petrópolis"},
{"jobTitle":"Help Desk Technician","companyName":"Tekfly","location":"Kamennogorsk"},
{"jobTitle":"Software Consultant","companyName":"Avamm","location":"Kramators’k"},
{"jobTitle":"Budget/Accounting Analyst II","companyName":"Avamm","location":"Sarrebourg"},
{"jobTitle":"Junior Executive","companyName":"Brainlounge","location":"Jiumen"},
{"jobTitle":"Librarian","companyName":"Flipopia","location":"Bang Len"},
{"jobTitle":"Programmer Analyst III","companyName":"Snaptags","location":"Kavadarci"},
{"jobTitle":"Account Coordinator","companyName":"Abata","location":"Cikarang"},
{"jobTitle":"Statistician I","companyName":"Quatz","location":"Hobscheid"},
{"jobTitle":"Environmental Specialist","companyName":"Mynte","location":"Airuk"},
{"jobTitle":"Quality Engineer","companyName":"Trudeo","location":"Tambobamba"},
{"jobTitle":"Health Coach I","companyName":"Mymm","location":"Zielonka"},
{"jobTitle":"Internal Auditor","companyName":"Talane","location":"Platičevo"},
{"jobTitle":"Research Associate","companyName":"Edgeblab","location":"Prado Siongco"},
{"jobTitle":"Automation Specialist II","companyName":"Janyx","location":"Verenchanka"},
{"jobTitle":"Research Assistant IV","companyName":"Eayo","location":"Gozdnica"},
{"jobTitle":"Account Representative II","companyName":"Jazzy","location":"Gaïtánion"},
{"jobTitle":"GIS Technical Architect","companyName":"Youspan","location":"Malindi"},
{"jobTitle":"Civil Engineer","companyName":"Blognation","location":"Ōhara"},
{"jobTitle":"Human Resources Assistant IV","companyName":"Jayo","location":"Villefranche-sur-Saône"},
{"jobTitle":"Graphic Designer","companyName":"Youopia","location":"Tsaghkadzor"},
{"jobTitle":"Administrative Assistant III","companyName":"Teklist","location":"Arklow"},
{"jobTitle":"Quality Control Specialist","companyName":"Zazio","location":"Alto de São Sebastião"},
{"jobTitle":"Office Assistant IV","companyName":"Snaptags","location":"Lat Lum Kaeo"},
{"jobTitle":"Senior Cost Accountant","companyName":"Devpoint","location":"Ziketan"},
{"jobTitle":"Software Test Engineer II","companyName":"Chatterpoint","location":"Caleufú"},
{"jobTitle":"Account Representative II","companyName":"Skalith","location":"Planeta Rica"},
{"jobTitle":"Technical Writer","companyName":"Kare","location":"Kaset Wisai"},
{"jobTitle":"Office Assistant I","companyName":"Aimbu","location":"Södertälje"},
{"jobTitle":"Human Resources Manager","companyName":"Ntags","location":"Vila Chã"},
{"jobTitle":"Analyst Programmer","companyName":"Livetube","location":"Yasnogorsk"},
{"jobTitle":"Electrical Engineer","companyName":"Voomm","location":"Güiria"},
{"jobTitle":"Health Coach I","companyName":"Riffpedia","location":"Bayambang"},
{"jobTitle":"Senior Cost Accountant","companyName":"Flashset","location":"Kelīshād va Sūdarjān"},
{"jobTitle":"Clinical Specialist","companyName":"Voonder","location":"Jiangyin"},
{"jobTitle":"Human Resources Assistant IV","companyName":"Centimia","location":"Haurpanggung"},
{"jobTitle":"Professor","companyName":"Tagfeed","location":"Icononzo"},
{"jobTitle":"Assistant Professor","companyName":"Blogspan","location":"Nakhon Ratchasima"},
{"jobTitle":"Assistant Manager","companyName":"Jaxnation","location":"Pung-Pang"},
{"jobTitle":"Administrative Assistant IV","companyName":"Meetz","location":"Atsipópoulon"},
{"jobTitle":"Research Nurse","companyName":"Photobug","location":"Lào Cai"},
{"jobTitle":"Community Outreach Specialist","companyName":"Gigabox","location":"Keroka"},
{"jobTitle":"VP Product Management","companyName":"Jabberbean","location":"Cornwall"},
{"jobTitle":"Professor","companyName":"Skalith","location":"Chengguan"},
{"jobTitle":"Civil Engineer","companyName":"Ainyx","location":"Wewoloe"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Youbridge","location":"Saint-Maurice-l'Exil"},
{"jobTitle":"Teacher","companyName":"Minyx","location":"Purut"},
{"jobTitle":"Desktop Support Technician","companyName":"Wordify","location":"Jiuchenggong"},
{"jobTitle":"Health Coach IV","companyName":"Eare","location":"Komatsushimachō"},
{"jobTitle":"Assistant Manager","companyName":"Meemm","location":"Gandu"},
{"jobTitle":"Electrical Engineer","companyName":"Yodoo","location":"Tahala"},
{"jobTitle":"VP Accounting","companyName":"Topiclounge","location":"Ngelak"},
{"jobTitle":"Developer III","companyName":"Mybuzz","location":"Itaboraí"},
{"jobTitle":"Analyst Programmer","companyName":"Vitz","location":"Zhalinghu"},
{"jobTitle":"Statistician III","companyName":"Jabbersphere","location":"Thị Trấn Quan Hóa"},
{"jobTitle":"Information Systems Manager","companyName":"Mydeo","location":"Catache"},
{"jobTitle":"Senior Quality Engineer","companyName":"Minyx","location":"Tenggina Daya"},
{"jobTitle":"Nurse Practicioner","companyName":"Realbuzz","location":"Xianzong"},
{"jobTitle":"Media Manager III","companyName":"Miboo","location":"Sukadana"},
{"jobTitle":"Sales Associate","companyName":"Livefish","location":"Mabuhay"},
{"jobTitle":"Account Coordinator","companyName":"Avamba","location":"Buqei‘a"},
{"jobTitle":"Design Engineer","companyName":"Lazzy","location":"Puntaru"},
{"jobTitle":"Senior Editor","companyName":"Zoomlounge","location":"Phù Cát"},
{"jobTitle":"Biostatistician III","companyName":"Brainbox","location":"São João dos Inhamuns"},
{"jobTitle":"Research Assistant II","companyName":"Voomm","location":"Ayapel"},
{"jobTitle":"Director of Sales","companyName":"Dabshots","location":"Yangjia"},
{"jobTitle":"Quality Engineer","companyName":"Buzzbean","location":"Santo Domingo"},
{"jobTitle":"Sales Associate","companyName":"Mynte","location":"Gucheng"},
{"jobTitle":"VP Product Management","companyName":"Youtags","location":"Ladoang"},
{"jobTitle":"Data Coordiator","companyName":"Aibox","location":"San Miguel"},
{"jobTitle":"Assistant Professor","companyName":"Flashdog","location":"Ngilengan"},
{"jobTitle":"VP Sales","companyName":"Linkbridge","location":"Rongxi"},
{"jobTitle":"Software Consultant","companyName":"Tekfly","location":"Länsi-Turunmaa"},
{"jobTitle":"Project Manager","companyName":"Aivee","location":"Pushkino"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Zoonoodle","location":"Roun Satu"},
{"jobTitle":"Environmental Specialist","companyName":"Oyoloo","location":"Petřvald"},
{"jobTitle":"Quality Control Specialist","companyName":"Fiveclub","location":"Chengnan"},
{"jobTitle":"Speech Pathologist","companyName":"Bubblemix","location":"Xiangfeng"},
{"jobTitle":"Engineer IV","companyName":"Skippad","location":"Oslo"},
{"jobTitle":"Junior Executive","companyName":"Jabberbean","location":"Yunxi"},
{"jobTitle":"Administrative Officer","companyName":"Meevee","location":"Jinjiahe"},
{"jobTitle":"Assistant Media Planner","companyName":"Eidel","location":"Hartford"},
{"jobTitle":"Compensation Analyst","companyName":"Photobug","location":"Zakhim"},
{"jobTitle":"Social Worker","companyName":"Trunyx","location":"Rättvik"},
{"jobTitle":"Compensation Analyst","companyName":"Twitterworks","location":"Massawa"},
{"jobTitle":"Account Representative I","companyName":"Twimbo","location":"Machov"},
{"jobTitle":"Senior Cost Accountant","companyName":"Gabvine","location":"Yangshufang"},
{"jobTitle":"Assistant Manager","companyName":"Wordpedia","location":"Artybash"},
{"jobTitle":"Accounting Assistant I","companyName":"Buzzshare","location":"Nuradilovo"},
{"jobTitle":"Budget/Accounting Analyst IV","companyName":"Roombo","location":"Gondanglegi Wetan"},
{"jobTitle":"Recruiting Manager","companyName":"Meezzy","location":"Bacnotan"},
{"jobTitle":"GIS Technical Architect","companyName":"Wordpedia","location":"Baltasar Brum"},
{"jobTitle":"VP Accounting","companyName":"Realcube","location":"Loukhi"},
{"jobTitle":"Research Assistant II","companyName":"Gigashots","location":"Vrbno pod Pradědem"},
{"jobTitle":"Web Designer I","companyName":"Yakijo","location":"Palmira"},
{"jobTitle":"Nurse","companyName":"Dablist","location":"Danxi"},
{"jobTitle":"Senior Cost Accountant","companyName":"Lazzy","location":"Herīs"},
{"jobTitle":"Quality Engineer","companyName":"Wordware","location":"Gustavia"},
{"jobTitle":"Biostatistician I","companyName":"Fivebridge","location":"Rumphi"},
{"jobTitle":"Human Resources Assistant III","companyName":"Meevee","location":"Jiuchenggong"},
{"jobTitle":"Human Resources Manager","companyName":"Izio","location":"Flandes"},
{"jobTitle":"Research Associate","companyName":"Feedspan","location":"Sim"},
{"jobTitle":"Food Chemist","companyName":"Midel","location":"Erhaodi"},
{"jobTitle":"Chemical Engineer","companyName":"Jaxnation","location":"Stírion"},
{"jobTitle":"Project Manager","companyName":"Skynoodle","location":"Sukumo"},
{"jobTitle":"Engineer III","companyName":"Feedbug","location":"Nanpu"},
{"jobTitle":"Legal Assistant","companyName":"Ntag","location":"Ouégoa"},
{"jobTitle":"Cost Accountant","companyName":"Dabvine","location":"Urrao"},
{"jobTitle":"Staff Scientist","companyName":"Zoombox","location":"Magrath"},
{"jobTitle":"Assistant Professor","companyName":"Cogidoo","location":"San Juan Ixcoy"},
{"jobTitle":"Environmental Specialist","companyName":"Realcube","location":"Vila Flor"},
{"jobTitle":"Environmental Specialist","companyName":"Oyope","location":"Galle"},
{"jobTitle":"Office Assistant III","companyName":"Jaxspan","location":"Grand-Bassam"},
{"jobTitle":"Paralegal","companyName":"Yotz","location":"Jingxi"},
{"jobTitle":"Programmer III","companyName":"Skilith","location":"Mashan"},
{"jobTitle":"Senior Sales Associate","companyName":"Zooveo","location":"Kachar"},
{"jobTitle":"Marketing Assistant","companyName":"Jabbercube","location":"Guaitarilla"},
{"jobTitle":"Internal Auditor","companyName":"Brainlounge","location":"Pombos"},
{"jobTitle":"Nurse","companyName":"Kayveo","location":"La Julia"},
{"jobTitle":"Nuclear Power Engineer","companyName":"Eazzy","location":"Budapest"},
{"jobTitle":"Sales Representative","companyName":"Quatz","location":"Wonokerto"},
{"jobTitle":"Computer Systems Analyst I","companyName":"Topicstorm","location":"Rana"},
{"jobTitle":"Systems Administrator I","companyName":"Chatterbridge","location":"Asnières-sur-Seine"},
{"jobTitle":"Safety Technician I","companyName":"Jetpulse","location":"Singaparna"},
{"jobTitle":"Senior Financial Analyst","companyName":"Devpoint","location":"Hirakata"},
{"jobTitle":"Help Desk Technician","companyName":"Tazz","location":"Chinú"},
{"jobTitle":"Dental Hygienist","companyName":"Dazzlesphere","location":"Santos Dumont"},
{"jobTitle":"Dental Hygienist","companyName":"Realcube","location":"Sumbergayam"},
{"jobTitle":"Cost Accountant","companyName":"Voomm","location":"Bijeli"},
{"jobTitle":"Dental Hygienist","companyName":"Thoughtmix","location":"Tandil"},
{"jobTitle":"GIS Technical Architect","companyName":"Mynte","location":"Kiten"},
{"jobTitle":"Junior Executive","companyName":"Gabtype","location":"Huolianpo"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Oyondu","location":"Bryukhovychi"},
{"jobTitle":"Media Manager I","companyName":"Realfire","location":"Oropesa"},
{"jobTitle":"Senior Quality Engineer","companyName":"Twitterbridge","location":"Banho e Carvalhosa"},
{"jobTitle":"Structural Engineer","companyName":"Vitz","location":"Kotuń"},
{"jobTitle":"Registered Nurse","companyName":"Topiczoom","location":"San Roque"},
{"jobTitle":"Accounting Assistant IV","companyName":"Dynazzy","location":"Tumba"},
{"jobTitle":"Sales Representative","companyName":"Jetpulse","location":"Syrskoye"},
{"jobTitle":"Technical Writer","companyName":"Bubblebox","location":"Cipicung"},
{"jobTitle":"Help Desk Operator","companyName":"Jazzy","location":"Ciroyom"},
{"jobTitle":"Geologist III","companyName":"Kwimbee","location":"Södra Sandby"},
{"jobTitle":"Software Engineer III","companyName":"Realfire","location":"Znomenka"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Topiclounge","location":"Kowingir"},
{"jobTitle":"Programmer II","companyName":"Skinte","location":"Dolní Dunajovice"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Nlounge","location":"Fukuroi"},
{"jobTitle":"Account Representative I","companyName":"Trilith","location":"Yerevan"},
{"jobTitle":"Account Representative IV","companyName":"Demimbu","location":"Banovo Polje"},
{"jobTitle":"Senior Sales Associate","companyName":"Flipbug","location":"Atolina"},
{"jobTitle":"Office Assistant III","companyName":"Avamba","location":"Soloneshnoye"},
{"jobTitle":"Speech Pathologist","companyName":"Rhynoodle","location":"Skoútari"},
{"jobTitle":"Environmental Specialist","companyName":"Trilith","location":"Comodoro Rivadavia"},
{"jobTitle":"Web Developer IV","companyName":"Demivee","location":"Lomintsevskiy"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Meezzy","location":"Lebak"},
{"jobTitle":"VP Product Management","companyName":"Photobean","location":"Pensacola"},
{"jobTitle":"Computer Systems Analyst II","companyName":"Thoughtsphere","location":"Maceo"},
{"jobTitle":"Recruiter","companyName":"Flipopia","location":"Galutu"},
{"jobTitle":"General Manager","companyName":"Skipstorm","location":"Mombok"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Meevee","location":"Kočevje"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Tagtune","location":"Ereira"},
{"jobTitle":"Programmer Analyst I","companyName":"Skimia","location":"Lyon"},
{"jobTitle":"Registered Nurse","companyName":"Rhynoodle","location":"Balekambang"},
{"jobTitle":"Financial Advisor","companyName":"Kwimbee","location":"Nagrumbuan"},
{"jobTitle":"Health Coach II","companyName":"Jatri","location":"Wololele A"},
{"jobTitle":"Human Resources Manager","companyName":"Skajo","location":"Golovchino"},
{"jobTitle":"Occupational Therapist","companyName":"Jayo","location":"Sukawaris"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Rhynyx","location":"Houston"},
{"jobTitle":"Pharmacist","companyName":"Agivu","location":"Budapest"},
{"jobTitle":"Assistant Media Planner","companyName":"Yambee","location":"Sarzedo"},
{"jobTitle":"VP Sales","companyName":"Gigaclub","location":"Una"},
{"jobTitle":"Executive Secretary","companyName":"Abatz","location":"Örebro"},
{"jobTitle":"Office Assistant I","companyName":"Voonder","location":"Millet"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Linklinks","location":"Al Wardānīn"},
{"jobTitle":"Software Engineer I","companyName":"Buzzshare","location":"Zhukovo"},
{"jobTitle":"Administrative Assistant IV","companyName":"Zoomdog","location":"Prince Rupert"},
{"jobTitle":"Administrative Assistant I","companyName":"Jabbercube","location":"Apalit"},
{"jobTitle":"Health Coach IV","companyName":"Cogidoo","location":"Nanmuping"},
{"jobTitle":"Nurse","companyName":"Meeveo","location":"Shangzhang"},
{"jobTitle":"Research Nurse","companyName":"Aibox","location":"Karavan"},
{"jobTitle":"Quality Engineer","companyName":"Browsezoom","location":"Wangcao"},
{"jobTitle":"Senior Quality Engineer","companyName":"Fanoodle","location":"Stepanovićevo"},
{"jobTitle":"Web Designer III","companyName":"Zoomdog","location":"Pulian"},
{"jobTitle":"Web Designer I","companyName":"Flashspan","location":"Marseille"},
{"jobTitle":"Food Chemist","companyName":"Myworks","location":"Kutacane"},
{"jobTitle":"Social Worker","companyName":"Realbuzz","location":"Nogent-sur-Marne"},
{"jobTitle":"Clinical Specialist","companyName":"Gigazoom","location":"Saint Louis"},
{"jobTitle":"Administrative Assistant IV","companyName":"Meevee","location":"Providencia"},
{"jobTitle":"Media Manager IV","companyName":"Topicblab","location":"Fangtang"},
{"jobTitle":"Developer III","companyName":"Abata","location":"Hispania"},
{"jobTitle":"Chief Design Engineer","companyName":"Eayo","location":"Chengfeng"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Snaptags","location":"Manolás"},
{"jobTitle":"Nurse Practicioner","companyName":"Youspan","location":"Hualian"},
{"jobTitle":"Project Manager","companyName":"Eadel","location":"Liqizhuang"},
{"jobTitle":"Web Designer III","companyName":"Zoomdog","location":"Bebedouro"},
{"jobTitle":"Programmer Analyst II","companyName":"Gigashots","location":"Xinzheng"},
{"jobTitle":"Human Resources Assistant I","companyName":"Roomm","location":"Ljubno ob Savinji"},
{"jobTitle":"Senior Sales Associate","companyName":"Dynava","location":"Ḩammām Damt"},
{"jobTitle":"Clinical Specialist","companyName":"Edgeblab","location":"Parksville"},
{"jobTitle":"Senior Editor","companyName":"Babbleopia","location":"Puunage"},
{"jobTitle":"Geologist III","companyName":"Mynte","location":"Kukoboy"},
{"jobTitle":"Civil Engineer","companyName":"Linkbuzz","location":"Santa Cruz"},
{"jobTitle":"Legal Assistant","companyName":"Wikibox","location":"Criação Velha"},
{"jobTitle":"Occupational Therapist","companyName":"Brainlounge","location":"Pustá Polom"},
{"jobTitle":"VP Quality Control","companyName":"Latz","location":"Jianmin"},
{"jobTitle":"Sales Representative","companyName":"Browsecat","location":"Gununganyartambak Tengah"},
{"jobTitle":"Programmer Analyst II","companyName":"DabZ","location":"Bueng Kan"},
{"jobTitle":"Professor","companyName":"Avavee","location":"Nouakchott"},
{"jobTitle":"Web Developer I","companyName":"Dabjam","location":"Mbaké"},
{"jobTitle":"Cost Accountant","companyName":"Quire","location":"Pingshan"},
{"jobTitle":"Marketing Assistant","companyName":"Skyba","location":"Bojongsari"},
{"jobTitle":"Research Assistant IV","companyName":"Centidel","location":"Burgeo"},
{"jobTitle":"Developer I","companyName":"Centidel","location":"Villa Lugano"},
{"jobTitle":"Information Systems Manager","companyName":"Avavee","location":"Alpūrai"},
{"jobTitle":"Financial Advisor","companyName":"Zooxo","location":"Isnos"},
{"jobTitle":"Administrative Officer","companyName":"Flipstorm","location":"Tabatinga"},
{"jobTitle":"Recruiting Manager","companyName":"Browseblab","location":"Kępice"},
{"jobTitle":"Teacher","companyName":"Gabspot","location":"Jataí"},
{"jobTitle":"Software Consultant","companyName":"Plambee","location":"Murcki"},
{"jobTitle":"VP Marketing","companyName":"Topdrive","location":"Phayuha Khiri"},
{"jobTitle":"Graphic Designer","companyName":"Jaxspan","location":"Nanyang"},
{"jobTitle":"Associate Professor","companyName":"Oyoba","location":"Velká Dobrá"},
{"jobTitle":"Financial Advisor","companyName":"Gigazoom","location":"Shangdian"},
{"jobTitle":"Safety Technician III","companyName":"Avavee","location":"Feijó"},
{"jobTitle":"Assistant Media Planner","companyName":"Jabbercube","location":"Anyama"},
{"jobTitle":"VP Quality Control","companyName":"Photospace","location":"Guangdu"},
{"jobTitle":"Developer II","companyName":"Edgeify","location":"Baishui"},
{"jobTitle":"Marketing Assistant","companyName":"Oyoloo","location":"Hekinan"},
{"jobTitle":"Accountant III","companyName":"Riffpedia","location":"Suai"},
{"jobTitle":"Recruiting Manager","companyName":"Youbridge","location":"Mengeš"},
{"jobTitle":"Assistant Media Planner","companyName":"Browseblab","location":"Kavieng"},
{"jobTitle":"Nurse Practicioner","companyName":"Digitube","location":"Muara"},
{"jobTitle":"Community Outreach Specialist","companyName":"Realcube","location":"Novhorodka"},
{"jobTitle":"Software Test Engineer IV","companyName":"Eidel","location":"Port Louis"},
{"jobTitle":"VP Quality Control","companyName":"Skyndu","location":"Newark"},
{"jobTitle":"Help Desk Operator","companyName":"Yamia","location":"Maebashi-shi"},
{"jobTitle":"Structural Engineer","companyName":"Buzzdog","location":"Bilajer"},
{"jobTitle":"Account Coordinator","companyName":"Thoughtstorm","location":"Fier-Çifçi"},
{"jobTitle":"Database Administrator II","companyName":"Cogilith","location":"Xianxiang"},
{"jobTitle":"Human Resources Manager","companyName":"Gevee","location":"Dudchany"},
{"jobTitle":"Assistant Manager","companyName":"Livetube","location":"Stradbally"},
{"jobTitle":"Teacher","companyName":"Fanoodle","location":"Willemstad"},
{"jobTitle":"Structural Engineer","companyName":"Mita","location":"Tucheng"},
{"jobTitle":"Occupational Therapist","companyName":"Browsedrive","location":"Heqing"},
{"jobTitle":"Account Representative III","companyName":"Yoveo","location":"Santa Catalina"},
{"jobTitle":"Computer Systems Analyst III","companyName":"Oyondu","location":"Valle Grande"},
{"jobTitle":"Quality Engineer","companyName":"Yambee","location":"Daxi"},
{"jobTitle":"Financial Analyst","companyName":"Camido","location":"Bangolo"},
{"jobTitle":"Senior Editor","companyName":"Flipopia","location":"Imbang"},
{"jobTitle":"Technical Writer","companyName":"Roomm","location":"Mississauga"},
{"jobTitle":"Professor","companyName":"Riffpedia","location":"Budapest"},
{"jobTitle":"VP Sales","companyName":"Twinte","location":"Novotroitsk"},
{"jobTitle":"Statistician I","companyName":"Jabbercube","location":"Krasnyy Yar"},
{"jobTitle":"Budget/Accounting Analyst IV","companyName":"Meeveo","location":"Shaozhai"},
{"jobTitle":"Paralegal","companyName":"Reallinks","location":"Kalimeneng"},
{"jobTitle":"Marketing Manager","companyName":"Eadel","location":"Waxi"},
{"jobTitle":"Cost Accountant","companyName":"Podcat","location":"Kalengwa"},
{"jobTitle":"Software Consultant","companyName":"Vinder","location":"Lintan Chengguanzhen"},
{"jobTitle":"Software Consultant","companyName":"Zoovu","location":"Xukou"},
{"jobTitle":"VP Marketing","companyName":"Bubblemix","location":"Cikarang"},
{"jobTitle":"Nurse","companyName":"Youfeed","location":"Hainan"},
{"jobTitle":"Office Assistant II","companyName":"InnoZ","location":"Freiburg im Breisgau"},
{"jobTitle":"Cost Accountant","companyName":"Thoughtworks","location":"Newark"},
{"jobTitle":"Chief Design Engineer","companyName":"Flashspan","location":"Helmsange"},
{"jobTitle":"Automation Specialist I","companyName":"Demizz","location":"Nyzhni Petrivtsi"},
{"jobTitle":"Assistant Manager","companyName":"Yoveo","location":"Skien"},
{"jobTitle":"Financial Advisor","companyName":"Teklist","location":"Sayaq"},
{"jobTitle":"Geologist III","companyName":"Lazz","location":"Konice"},
{"jobTitle":"Technical Writer","companyName":"Meetz","location":"Wuyanquan"},
{"jobTitle":"Senior Cost Accountant","companyName":"Realblab","location":"Yanjiang"},
{"jobTitle":"Quality Engineer","companyName":"Yabox","location":"Carcavelos"},
{"jobTitle":"Help Desk Technician","companyName":"Roombo","location":"Cầu Giấy"},
{"jobTitle":"VP Sales","companyName":"Photofeed","location":"Barong"},
{"jobTitle":"Automation Specialist II","companyName":"Topicshots","location":"Lindi"},
{"jobTitle":"Database Administrator II","companyName":"Feednation","location":"Tampere"},
{"jobTitle":"Pharmacist","companyName":"Kayveo","location":"Sydney"},
{"jobTitle":"Staff Accountant I","companyName":"Plajo","location":"Namie"},
{"jobTitle":"Environmental Specialist","companyName":"Voomm","location":"Descalvado"},
{"jobTitle":"Food Chemist","companyName":"Yakitri","location":"Kamennogorsk"},
{"jobTitle":"Pharmacist","companyName":"Photojam","location":"Chitré"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Buzzdog","location":"Luže"},
{"jobTitle":"Sales Representative","companyName":"Pixoboo","location":"Açucena"},
{"jobTitle":"Research Associate","companyName":"Eimbee","location":"Lapas"},
{"jobTitle":"Staff Scientist","companyName":"Oyoba","location":"Carmo do Paranaíba"},
{"jobTitle":"Editor","companyName":"Eidel","location":"Pandian"},
{"jobTitle":"Research Nurse","companyName":"Brainverse","location":"Duishan"},
{"jobTitle":"Professor","companyName":"Oozz","location":"Los Santos"},
{"jobTitle":"Research Associate","companyName":"Shuffletag","location":"Panalanoy"},
{"jobTitle":"Account Executive","companyName":"Trilia","location":"Prosyana"},
{"jobTitle":"Project Manager","companyName":"Feedfish","location":"Karangintan"},
{"jobTitle":"Graphic Designer","companyName":"Jaxworks","location":"Paccha"},
{"jobTitle":"Assistant Professor","companyName":"Ailane","location":"Dežanovac"},
{"jobTitle":"VP Product Management","companyName":"Photobean","location":"Varberg"},
{"jobTitle":"Media Manager IV","companyName":"Kwinu","location":"Sherpur"},
{"jobTitle":"Assistant Manager","companyName":"Quamba","location":"Rennes"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Kwilith","location":"Sabaneta"},
{"jobTitle":"Legal Assistant","companyName":"Omba","location":"Dawuhanmangli"},
{"jobTitle":"Staff Accountant III","companyName":"Divape","location":"Sagay"},
{"jobTitle":"Senior Quality Engineer","companyName":"Rhybox","location":"Jiangfang"},
{"jobTitle":"Financial Analyst","companyName":"Wordpedia","location":"Hekou"},
{"jobTitle":"Administrative Officer","companyName":"Yodo","location":"Olopa"},
{"jobTitle":"Accountant I","companyName":"Wikizz","location":"Shirgjan"},
{"jobTitle":"Project Manager","companyName":"Brainverse","location":"Concepcion"},
{"jobTitle":"Sales Representative","companyName":"Divanoodle","location":"Sampangbitung"},
{"jobTitle":"Quality Control Specialist","companyName":"Mybuzz","location":"Akita Shi"},
{"jobTitle":"VP Sales","companyName":"Yadel","location":"Ivot"},
{"jobTitle":"Financial Analyst","companyName":"Zava","location":"Nieuwegein"},
{"jobTitle":"Occupational Therapist","companyName":"Yotz","location":"Magnitka"},
{"jobTitle":"Research Associate","companyName":"Jabbersphere","location":"Извор"},
{"jobTitle":"Structural Analysis Engineer","companyName":"Yakitri","location":"Abua"},
{"jobTitle":"Developer IV","companyName":"Gevee","location":"Orocué"},
{"jobTitle":"Human Resources Assistant I","companyName":"Skimia","location":"Campana"},
{"jobTitle":"Executive Secretary","companyName":"Divape","location":"Kynopiástes"},
{"jobTitle":"Accounting Assistant I","companyName":"Aibox","location":"Herval"},
{"jobTitle":"Project Manager","companyName":"Skyba","location":"Hachinohe"},
{"jobTitle":"Recruiter","companyName":"Zazio","location":"Eskilstuna"},
{"jobTitle":"Data Coordiator","companyName":"Ailane","location":"Stockholm"},
{"jobTitle":"VP Quality Control","companyName":"Twitterworks","location":"Butou"},
{"jobTitle":"Research Associate","companyName":"Kwideo","location":"Longquan"},
{"jobTitle":"Software Test Engineer II","companyName":"Pixonyx","location":"Berbera"},
{"jobTitle":"VP Accounting","companyName":"Skimia","location":"Tbilisskaya"},
{"jobTitle":"Human Resources Assistant IV","companyName":"Vidoo","location":"Maastricht"},
{"jobTitle":"Operator","companyName":"Quatz","location":"Río Sereno"},
{"jobTitle":"Quality Engineer","companyName":"Centizu","location":"Huangshi"},
{"jobTitle":"Operator","companyName":"Realmix","location":"Yaguarón"},
{"jobTitle":"Editor","companyName":"Topiczoom","location":"Łęki Szlacheckie"},
{"jobTitle":"Recruiter","companyName":"Trilia","location":"Novo Cruzeiro"},
{"jobTitle":"Social Worker","companyName":"Youtags","location":"Magugu"},
{"jobTitle":"Human Resources Manager","companyName":"Zoomzone","location":"Dayr al Ghuşūn"},
{"jobTitle":"Human Resources Manager","companyName":"Camimbo","location":"Marte"},
{"jobTitle":"Analyst Programmer","companyName":"Skinder","location":"Huzhen"},
{"jobTitle":"Speech Pathologist","companyName":"Skinte","location":"Puyo"},
{"jobTitle":"Health Coach II","companyName":"Twimm","location":"Lengji"},
{"jobTitle":"Internal Auditor","companyName":"Zoozzy","location":"Noebesa"},
{"jobTitle":"Programmer I","companyName":"Devbug","location":"Baishui"},
{"jobTitle":"GIS Technical Architect","companyName":"Livetube","location":"Kinmparana"},
{"jobTitle":"Operator","companyName":"Oyoyo","location":"Sollefteå"},
{"jobTitle":"Product Engineer","companyName":"Yata","location":"Leipsoí"},
{"jobTitle":"Accounting Assistant I","companyName":"Geba","location":"Melikkrajan"},
{"jobTitle":"Professor","companyName":"Teklist","location":"Pulau Pinang"},
{"jobTitle":"Geological Engineer","companyName":"Linkbuzz","location":"Kangani"},
{"jobTitle":"Software Consultant","companyName":"Skimia","location":"Kotayk’"},
{"jobTitle":"Accounting Assistant IV","companyName":"Gevee","location":"San Gil"},
{"jobTitle":"Human Resources Manager","companyName":"Abata","location":"Abades"},
{"jobTitle":"Engineer I","companyName":"Meemm","location":"Jintang"},
{"jobTitle":"Junior Executive","companyName":"Dabjam","location":"Ijero-Ekiti"},
{"jobTitle":"Web Developer II","companyName":"Edgewire","location":"Saint-Joseph-de-Coleraine"},
{"jobTitle":"Pharmacist","companyName":"Edgeclub","location":"Yajin"},
{"jobTitle":"Health Coach III","companyName":"Oyope","location":"Adar"},
{"jobTitle":"Research Assistant I","companyName":"Chatterbridge","location":"Taiyang"},
{"jobTitle":"Staff Scientist","companyName":"Mynte","location":"Jitian"},
{"jobTitle":"Research Associate","companyName":"Feednation","location":"Venda do Alcaide"},
{"jobTitle":"Health Coach I","companyName":"Meetz","location":"Haifa"},
{"jobTitle":"VP Product Management","companyName":"Skyble","location":"Regidor"},
{"jobTitle":"Environmental Specialist","companyName":"Aimbo","location":"Amfíkleia"},
{"jobTitle":"Senior Cost Accountant","companyName":"Kazio","location":"Xianghu"},
{"jobTitle":"Internal Auditor","companyName":"Yodel","location":"Grojec"},
{"jobTitle":"Clinical Specialist","companyName":"Meemm","location":"Presidente Epitácio"},
{"jobTitle":"Civil Engineer","companyName":"Skipfire","location":"Villa Paula de Sarmiento"},
{"jobTitle":"Accounting Assistant IV","companyName":"Riffpedia","location":"Sorocaba"},
{"jobTitle":"Physical Therapy Assistant","companyName":"Realcube","location":"Augustów"},
{"jobTitle":"Chemical Engineer","companyName":"Youfeed","location":"Huta Stara B"},
{"jobTitle":"Web Designer III","companyName":"Pixoboo","location":"Lons-le-Saunier"},
{"jobTitle":"Marketing Manager","companyName":"Fiveclub","location":"Ujiie"},
{"jobTitle":"VP Sales","companyName":"Roodel","location":"Mercedes"},
{"jobTitle":"Information Systems Manager","companyName":"Jetpulse","location":"Agen"},
{"jobTitle":"Administrative Officer","companyName":"Mynte","location":"San Pedro"},
{"jobTitle":"Environmental Tech","companyName":"Skimia","location":"Halden"},
{"jobTitle":"Account Representative IV","companyName":"Topicstorm","location":"Sidokumpul"},
{"jobTitle":"Technical Writer","companyName":"Wordify","location":"Göteborg"},
{"jobTitle":"Software Test Engineer II","companyName":"Realfire","location":"Curuan"},
{"jobTitle":"VP Sales","companyName":"Blogpad","location":"Citampian"},
{"jobTitle":"Internal Auditor","companyName":"Wordify","location":"Yuyangguan"},
{"jobTitle":"Graphic Designer","companyName":"Mynte","location":"Castanheira de Pêra"},
{"jobTitle":"Software Test Engineer I","companyName":"Realfire","location":"Salamá"},
{"jobTitle":"GIS Technical Architect","companyName":"Jetwire","location":"Catujal Velho"},
{"jobTitle":"Systems Administrator II","companyName":"Jetpulse","location":"Shujāābād"},
{"jobTitle":"Junior Executive","companyName":"Minyx","location":"Stavanger"},
{"jobTitle":"Assistant Professor","companyName":"Twitternation","location":"Peuteuy"},
{"jobTitle":"Assistant Manager","companyName":"Eare","location":"Wantian"},
{"jobTitle":"Software Consultant","companyName":"Roomm","location":"Limoeiro do Norte"},
{"jobTitle":"Structural Engineer","companyName":"Trilith","location":"Viana do Castelo"},
{"jobTitle":"Electrical Engineer","companyName":"Podcat","location":"Berat"},
{"jobTitle":"Paralegal","companyName":"Mydeo","location":"Kuangyuan"},
{"jobTitle":"Tax Accountant","companyName":"Skyble","location":"Kota Kinabalu"},
{"jobTitle":"Human Resources Assistant IV","companyName":"Oba","location":"Arcangel"},
{"jobTitle":"Librarian","companyName":"Browsezoom","location":"Boyu"},
{"jobTitle":"Senior Financial Analyst","companyName":"Innojam","location":"Pananaw"},
{"jobTitle":"Systems Administrator I","companyName":"Jabbercube","location":"Maslovka"},
{"jobTitle":"VP Product Management","companyName":"Jabbercube","location":"Miskolc"},
{"jobTitle":"Compensation Analyst","companyName":"Flashdog","location":"Chīchāwatni"},
{"jobTitle":"Assistant Professor","companyName":"Yakijo","location":"Dajin"},
{"jobTitle":"Quality Engineer","companyName":"Youspan","location":"Monte de Trigo"},
{"jobTitle":"Electrical Engineer","companyName":"Tazzy","location":"Tuapukan"},
{"jobTitle":"Senior Editor","companyName":"Buzzster","location":"Tomé Açu"},
{"jobTitle":"General Manager","companyName":"Kwimbee","location":"Shangcun"},
{"jobTitle":"Actuary","companyName":"Dablist","location":"Woha"},
{"jobTitle":"Information Systems Manager","companyName":"Skiba","location":"Sangtian"},
{"jobTitle":"Software Test Engineer II","companyName":"Ooba","location":"Kulase"},
{"jobTitle":"Internal Auditor","companyName":"Quire","location":"Cagliari"},
{"jobTitle":"Help Desk Operator","companyName":"Yakidoo","location":"Yuhe"},
{"jobTitle":"Community Outreach Specialist","companyName":"Devcast","location":"Winston Salem"},
{"jobTitle":"Administrative Assistant I","companyName":"Yozio","location":"Bayzhansay"},
{"jobTitle":"Financial Advisor","companyName":"Npath","location":"Xiji"},
{"jobTitle":"Budget/Accounting Analyst II","companyName":"Skalith","location":"Pishaj"},
{"jobTitle":"Pharmacist","companyName":"Teklist","location":"Popovo"},
{"jobTitle":"Clinical Specialist","companyName":"Eamia","location":"Błażowa"},
{"jobTitle":"Cost Accountant","companyName":"Livetube","location":"Richmond"},
{"jobTitle":"Dental Hygienist","companyName":"Bluejam","location":"Sade"},
{"jobTitle":"Community Outreach Specialist","companyName":"Flashspan","location":"Lanta Timur"},
{"jobTitle":"Administrative Assistant III","companyName":"Ainyx","location":"Clondalkin"},
{"jobTitle":"Marketing Manager","companyName":"Npath","location":"Taganskiy"},
{"jobTitle":"Geological Engineer","companyName":"Brainlounge","location":"Nakamura"},
{"jobTitle":"Design Engineer","companyName":"Chatterbridge","location":"Sobontoro"},
{"jobTitle":"Analyst Programmer","companyName":"Voomm","location":"Manquiring"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Tagcat","location":"Mubo"},
{"jobTitle":"Database Administrator I","companyName":"Yakidoo","location":"Pawa"},
{"jobTitle":"Senior Developer","companyName":"Innotype","location":"Peoria"},
{"jobTitle":"Senior Cost Accountant","companyName":"Photofeed","location":"Meitang"},
{"jobTitle":"Research Nurse","companyName":"Avamba","location":"Santa Catalina"},
{"jobTitle":"Software Engineer IV","companyName":"Skyvu","location":"Sukamaju"},
{"jobTitle":"Information Systems Manager","companyName":"Yacero","location":"Cofimvaba"},
{"jobTitle":"Accounting Assistant II","companyName":"Flashpoint","location":"Yaozhuang"},
{"jobTitle":"Nurse Practicioner","companyName":"Brightbean","location":"Yelabuga"},
{"jobTitle":"Senior Cost Accountant","companyName":"Oloo","location":"Toulon"},
{"jobTitle":"Database Administrator IV","companyName":"Gevee","location":"Grabów nad Prosną"},
{"jobTitle":"Professor","companyName":"Photobug","location":"Arendal"},
{"jobTitle":"Structural Engineer","companyName":"Dabvine","location":"Cipesing"},
{"jobTitle":"Statistician I","companyName":"Bluezoom","location":"Chishui"},
{"jobTitle":"Programmer Analyst III","companyName":"Oyoyo","location":"Aghada"},
{"jobTitle":"Financial Advisor","companyName":"Oyope","location":"Klenčí pod Čerchovem"},
{"jobTitle":"Budget/Accounting Analyst II","companyName":"Einti","location":"Magsalangi"},
{"jobTitle":"Senior Financial Analyst","companyName":"Reallinks","location":"Tiarei"},
{"jobTitle":"Librarian","companyName":"Jetwire","location":"Mchinji"},
{"jobTitle":"VP Sales","companyName":"Trilith","location":"Demir Hisar"},
{"jobTitle":"Programmer Analyst I","companyName":"Zoonder","location":"Sandefjord"},
{"jobTitle":"Nurse","companyName":"Wordware","location":"Gengqing"},
{"jobTitle":"Systems Administrator II","companyName":"Babbleopia","location":"Ikšķile"},
{"jobTitle":"Staff Accountant IV","companyName":"Zooxo","location":"Trinity"},
{"jobTitle":"Senior Cost Accountant","companyName":"Fanoodle","location":"Yasinya"},
{"jobTitle":"Human Resources Assistant III","companyName":"Einti","location":"Dongshangen"},
{"jobTitle":"Actuary","companyName":"Skimia","location":"Radostowice"},
{"jobTitle":"Graphic Designer","companyName":"Kwinu","location":"Azurduy"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Avamba","location":"Yokotemachi"},
{"jobTitle":"Quality Control Specialist","companyName":"JumpXS","location":"Mijiang"},
{"jobTitle":"Cost Accountant","companyName":"Brainverse","location":"Taoyuan"},
{"jobTitle":"Web Developer IV","companyName":"Cogilith","location":"Lillooet"},
{"jobTitle":"Business Systems Development Analyst","companyName":"Midel","location":"Jiaoqiao"},
{"jobTitle":"Analyst Programmer","companyName":"Avaveo","location":"Waerana"},
{"jobTitle":"Human Resources Manager","companyName":"Divavu","location":"Rawuk"},
{"jobTitle":"Sales Associate","companyName":"Brightdog","location":"Sudimara"},
{"jobTitle":"Developer I","companyName":"Skimia","location":"Vlorë"},
{"jobTitle":"Research Associate","companyName":"Rhycero","location":"Filipowice"},
{"jobTitle":"Software Test Engineer III","companyName":"Devcast","location":"Al Matūn"},
{"jobTitle":"Accountant II","companyName":"Yozio","location":"Avesta"},
{"jobTitle":"Quality Engineer","companyName":"Blogpad","location":"Stockholm"},
{"jobTitle":"Web Designer IV","companyName":"Talane","location":"Heshan"},
{"jobTitle":"Help Desk Technician","companyName":"Aimbu","location":"Mshinskaya"},
{"jobTitle":"GIS Technical Architect","companyName":"Ainyx","location":"Florencio Varela"},
{"jobTitle":"Geologist II","companyName":"Wordtune","location":"Tuateta"},
{"jobTitle":"Structural Engineer","companyName":"Voonte","location":"Kallithéa"},
{"jobTitle":"Speech Pathologist","companyName":"Devpulse","location":"Quxi"},
{"jobTitle":"Technical Writer","companyName":"Dabshots","location":"Leuwayang"},
{"jobTitle":"Marketing Assistant","companyName":"Demizz","location":"Kuivaniemi"},
{"jobTitle":"Cost Accountant","companyName":"Centizu","location":"Korogan Timur"},
{"jobTitle":"Senior Financial Analyst","companyName":"Dabtype","location":"Sakura"},
{"jobTitle":"Senior Quality Engineer","companyName":"Skipfire","location":"Laventure"},
{"jobTitle":"Media Manager II","companyName":"Yacero","location":"Ikeja"},
{"jobTitle":"Administrative Officer","companyName":"Eamia","location":"Oetutulul"},
{"jobTitle":"Media Manager IV","companyName":"Ozu","location":"Huaccana"},
{"jobTitle":"Biostatistician II","companyName":"Skibox","location":"Al Lubban al Gharbī"},
{"jobTitle":"Engineer I","companyName":"Skajo","location":"Xiaolukou"},
{"jobTitle":"Professor","companyName":"Trunyx","location":"Panambi"},
{"jobTitle":"Research Assistant II","companyName":"Cogilith","location":"Pasirputih"},
{"jobTitle":"Senior Quality Engineer","companyName":"Lazzy","location":"La Garenne-Colombes"},
{"jobTitle":"Automation Specialist II","companyName":"Bubblebox","location":"Kitale"},
{"jobTitle":"Sales Associate","companyName":"Brightbean","location":"Pop"},
{"jobTitle":"Assistant Manager","companyName":"Yoveo","location":"Bandhagen"},
{"jobTitle":"Payment Adjustment Coordinator","companyName":"Linktype","location":"Huangludian"},
{"jobTitle":"Mechanical Systems Engineer","companyName":"Photobean","location":"Boyu"},
{"jobTitle":"VP Quality Control","companyName":"Rhynoodle","location":"Huolianpo"},
{"jobTitle":"Senior Sales Associate","companyName":"Centizu","location":"Lisewo Malborskie"},
{"jobTitle":"Geologist IV","companyName":"Wikizz","location":"Hanshou"},
{"jobTitle":"Cost Accountant","companyName":"Photobean","location":"Lampa"},
{"jobTitle":"Operator","companyName":"Yombu","location":"Wulongshan"},
{"jobTitle":"Senior Developer","companyName":"Twitterwire","location":"North Side"},
{"jobTitle":"Director of Sales","companyName":"Eare","location":"Straldzha"},
{"jobTitle":"Associate Professor","companyName":"Thoughtmix","location":"Szeged"},
{"jobTitle":"Human Resources Manager","companyName":"Linklinks","location":"Malusac"},
{"jobTitle":"Quality Engineer","companyName":"Bubblemix","location":"Sitiarjo"},
{"jobTitle":"Associate Professor","companyName":"Skynoodle","location":"Cikaung"},
{"jobTitle":"Programmer I","companyName":"Mymm","location":"Sanjiang"},
{"jobTitle":"VP Marketing","companyName":"Ntag","location":"Sexmoan"},
{"jobTitle":"Account Executive","companyName":"Thoughtblab","location":"Hwange"},
{"jobTitle":"Recruiter","companyName":"Skinix","location":"Gafargaon"},
{"jobTitle":"Human Resources Manager","companyName":"Topiczoom","location":"Santa Rita"},
{"jobTitle":"Chemical Engineer","companyName":"Browsecat","location":"Nisporeni"},
{"jobTitle":"Junior Executive","companyName":"Realfire","location":"Jawornik"},
{"jobTitle":"VP Accounting","companyName":"Dynazzy","location":"Jiaoyuan"},
{"jobTitle":"Senior Developer","companyName":"Pixope","location":"Ipoti"},
{"jobTitle":"Senior Sales Associate","companyName":"Gigabox","location":"Malabor"},
{"jobTitle":"Assistant Professor","companyName":"Realpoint","location":"Horní Suchá"},
{"jobTitle":"Web Developer I","companyName":"Midel","location":"Herong"},
{"jobTitle":"Accounting Assistant IV","companyName":"Thoughtmix","location":"Nowy Dwór Gdański"},
{"jobTitle":"Safety Technician I","companyName":"Wordtune","location":"Luknovo"},
{"jobTitle":"Social Worker","companyName":"Realcube","location":"Huibu"},
{"jobTitle":"Help Desk Technician","companyName":"Photofeed","location":"Banjar Delodrurung"},
{"jobTitle":"Project Manager","companyName":"Voonte","location":"Heshang"},
{"jobTitle":"Marketing Manager","companyName":"Jetwire","location":"Shiogama"},
{"jobTitle":"Senior Financial Analyst","companyName":"Yambee","location":"Khromtau"},
{"jobTitle":"Environmental Specialist","companyName":"Topdrive","location":"Stamford"},
{"jobTitle":"Help Desk Operator","companyName":"Photobug","location":"Studzienice"},
{"jobTitle":"VP Marketing","companyName":"Demizz","location":"Medeiros Neto"},
{"jobTitle":"Senior Developer","companyName":"Brainbox","location":"Zeleneč"},
{"jobTitle":"Teacher","companyName":"Vinder","location":"Guandian"},
{"jobTitle":"Design Engineer","companyName":"Oba","location":"Mangli"},
{"jobTitle":"Account Executive","companyName":"Dablist","location":"Foumban"},
{"jobTitle":"VP Marketing","companyName":"Skimia","location":"Três de Maio"},
{"jobTitle":"Programmer II","companyName":"Gigaclub","location":"Šventoji"},
{"jobTitle":"Clinical Specialist","companyName":"Yakitri","location":"Paterson"},
{"jobTitle":"Financial Analyst","companyName":"Wordtune","location":"Yuekou"},
{"jobTitle":"Product Engineer","companyName":"Gabspot","location":"Isla Pucú"},
{"jobTitle":"Biostatistician II","companyName":"Quatz","location":"Kungälv"},
{"jobTitle":"Administrative Officer","companyName":"Divavu","location":"Glinka"},
{"jobTitle":"Speech Pathologist","companyName":"Thoughtworks","location":"El Paso"},
{"jobTitle":"Sales Associate","companyName":"Gabvine","location":"Douane"},
{"jobTitle":"Nurse Practicioner","companyName":"Thoughtworks","location":"Cumanacoa"},
{"jobTitle":"Assistant Media Planner","companyName":"Camimbo","location":"Shamkhor"},
{"jobTitle":"Environmental Specialist","companyName":"Dabvine","location":"Kuusjoki"},
{"jobTitle":"Office Assistant II","companyName":"Brightdog","location":"Santa Luzia"},
{"jobTitle":"Quality Engineer","companyName":"Agimba","location":"Quba"},
{"jobTitle":"Dental Hygienist","companyName":"Yotz","location":"Hufang"},
{"jobTitle":"Safety Technician I","companyName":"Mudo","location":"Pantaihambawang"},
{"jobTitle":"Compensation Analyst","companyName":"Skipfire","location":"Liangnong"},
{"jobTitle":"Assistant Media Planner","companyName":"Quaxo","location":"Donduşeni"},
{"jobTitle":"Sales Associate","companyName":"Tekfly","location":"Alqueidão"},
{"jobTitle":"Software Consultant","companyName":"Tagchat","location":"Asahikawa"},
{"jobTitle":"Technical Writer","companyName":"Eadel","location":"Waterbury"},
{"jobTitle":"Automation Specialist I","companyName":"Flipstorm","location":"Kotli Lohārān"},
{"jobTitle":"Research Associate","companyName":"Bubblebox","location":"Podwilk"},
{"jobTitle":"Dental Hygienist","companyName":"Fivebridge","location":"Newark"},
{"jobTitle":"Safety Technician I","companyName":"Dynava","location":"Bayeux"},
{"jobTitle":"Automation Specialist III","companyName":"Gabcube","location":"Pandasan"},
{"jobTitle":"Analog Circuit Design manager","companyName":"Thoughtblab","location":"Bukedea"},
{"jobTitle":"Speech Pathologist","companyName":"Mudo","location":"Hồ Xá"},
{"jobTitle":"Sales Representative","companyName":"Flipstorm","location":"Nai Harn"},
{"jobTitle":"Accountant II","companyName":"Yakitri","location":"Piła"},
{"jobTitle":"Accountant II","companyName":"Muxo","location":"Yuhuang"},
{"jobTitle":"Financial Advisor","companyName":"Oyoba","location":"Banatska Topola"},
{"jobTitle":"Assistant Media Planner","companyName":"Gabvine","location":"Bielefeld"},
{"jobTitle":"Occupational Therapist","companyName":"Eadel","location":"Hamhŭng"},
{"jobTitle":"Sales Representative","companyName":"Trilith","location":"Denver"},
{"jobTitle":"Computer Systems Analyst IV","companyName":"Chatterpoint","location":"Sampaio"},
{"jobTitle":"Nurse","companyName":"Edgetag","location":"Nizhniy Tagil"},
{"jobTitle":"Software Consultant","companyName":"Realfire","location":"Ngkiong"},
{"jobTitle":"Cost Accountant","companyName":"Dabshots","location":"Cimanggu"},
{"jobTitle":"Programmer Analyst I","companyName":"Devpoint","location":"Santulhão"},
{"jobTitle":"Web Developer III","companyName":"Izio","location":"Đắk Mil"}], function (item, done) {
	async.setImmediate(function () {
		client.create({
			index : 'db',
			type : 'jobs',
			body : item
		}, done);
	});
}, ok);
	}
], callback);


